spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ms-account?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=UTC
    username: account
    password: account

server:
  port: 9120

oauth2:
    resource-server:
        check-token-url: http://localhost:9110/oauth/check_token
        client-id: browser
        client-secret: browser

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8110/eureka/

mybatis:
  mapper-locations: classpath:mapper/*.xml

