server:
  port: 8120

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeout-in-milliseconds: 60000

ribbon:
  read-timeout: 60000
  connect-timeout: 60000

zuul:
  ignored-services: '*'
  host:
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000
  routes:
    cms-ms-auth:
      path: /auth/**
      serviceId: cms-ms-auth
      sensitiveHeaders:
    cms-ms-account:
      path: /accounts/**
      serviceId: cms-ms-account
      sensitiveHeaders:
    cms-ms-statistics:
      path: /statistics/**
      serviceId: cms-ms-statistics
      sensitiveHeaders:

eureka:
  instance:
    prefer-ip-address: true
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://localhost:8110/eureka/
