spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ms-auth?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=UTC
    username: auth
    password: auth

server:
  port: 9110

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8110/eureka/


oauth2-client:
    clients:
        - clientId: browser
          secret: browser
          scopes: ui
          grantTypes: password, refresh_token
          accessTokenValiditySeconds: 3600
          refreshTokenValiditySeconds: 360000

        - clientId: ms-account
          secret: 123456
          scopes: server
          grantTypes: client_credentials, refresh_token
          accessTokenValiditySeconds: 3600
          refreshTokenValiditySeconds: 360000

        - clientId: ms-notification
          secret: 123456
          scopes: server
          grantTypes: client_credentials, refresh_token
          accessTokenValiditySeconds: 3600
          refreshTokenValiditySeconds: 360000

        - clientId: ms-statistics
          secret: 123456
          scopes: server
          grantTypes: client_credentials, refresh_token
          accessTokenValiditySeconds: 3600
          refreshTokenValiditySeconds: 360000

mybatis:
  mapper-locations: classpath:mapper/*.xml
