CREATE TABLE t_user (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '用户主键',
  `username` VARCHAR(100) NOT NULL COMMENT '用户名',
  `password` VARCHAR(100) NOT NULL COMMENT '用户密码',
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_username`(`username`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET='utf8' COMMENT='用户表';

CREATE TABLE `t_account` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
  `account_name` VARCHAR(100) NOT NULL COMMENT '用户名',
  `note` VARCHAR(100) NOT NULL COMMENT '备注',
  `last_seen` DATE NOT NULL COMMENT '最近一次登陆',
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_name`(`account_name`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET='utf8' COMMENT='账户表';

CREATE TABLE t_item (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
  `title` VARCHAR(100) NOT NULL COMMENT '标题',
  `amount` VARCHAR(100) NOT NULL COMMENT '总计',
  `currency` VARCHAR(16) NOT NULL COMMENT '货币类型',
  `period` VARCHAR(16) NOT NULL COMMENT '时间周期',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET='utf8' COMMENT='账户项表';

CREATE TABLE t_saving (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
  `amount` DECIMAL(16,2) NOT NULL COMMENT '总计',
  `currency` VARCHAR(16) NOT NULL COMMENT '货币类型',
  `interest` decimal(16,2) NOT NULL COMMENT '利益',
  `deposit` TINYINT NOT NULL COMMENT '押金',
  `capitalization` TINYINT NOT NULL COMMENT '资本化',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET='utf8' COMMENT='储蓄表';